/** @type {import('stylelint').Config} */
export default {
  extends: ['stylelint-config-standard-vue/scss'],
  overrides: [
    {
      files: ['**/*.scss'],
      customSyntax: 'postcss-scss',
    },
  ],
  ignoreFiles: ['*.svg', '*.xml'],
  plugins: ['stylelint-scss', 'stylelint-order'],
  rules: {
    'at-rule-no-unknown': null,
    'scss/at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: [
          'apply',
          'extend',
          'include',
          'mixin',
          'if',
          'for',
          'each',
          'while',
        ],
      },
    ],
    'declaration-block-no-duplicate-properties': null,
    'font-family-no-missing-generic-family-keyword': null,
    'no-descending-specificity': null,
    'order/properties-order': [
      {
        groupName: 'display',
        properties: ['display', 'align-items', 'justify-content'],
      },
      {
        groupName: 'positioning',
        properties: ['position', 'top', 'right', 'bottom', 'left'],
      },
      {
        groupName: 'box-model',
        properties: [
          'width',
          'max-width',
          'min-width',
          'height',
          'max-height',
          'min-height',
          'padding',
          'padding-top',
          'padding-right',
          'padding-bottom',
          'padding-left',
          'margin',
          'margin-top',
          'margin-right',
          'margin-bottom',
          'margin-left',
          'border',
          'border-top',
          'border-right',
          'border-bottom',
          'border-left',
          'border-radius',
        ],
      },
      {
        groupName: 'background/color',
        properties: [
          'color',
          'background',
          'background-color',
          'background-image',
          'background-position',
          'background-size',
          'background-repeat',
        ],
      },
      {
        groupName: 'typography',
        properties: [
          'font-style',
          'font-variant',
          'font-weight',
          'font-size',
          'line-height',
          'font-family',
        ],
      },
      {
        groupName: 'misc',
        properties: [
          'animation',
          'animation-name',
          'animation-duration',
          'animation-timing-function',
          'animation-delay',
          'animation-direction',
          'animation-iteration-count',
          'animation-fill-mode',
          'animation-play-state',
          'transition',
          'opacity',
          'z-index',
        ],
      },
    ],
    'order/order': [
      'custom-properties',
      'dollar-variables',
      'declarations',
      'at-rules',
      'rules',
    ],
    'import-notation': 'string',
    'no-invalid-double-slash-comments': null,
    'function-no-unknown': [true, { ignoreFunctions: ['lighten', 'darken'] }],
    'scss/load-partial-extension': 'never',
    'scss/dollar-variable-colon-space-after': 'always',
    'scss/dollar-variable-colon-space-before': 'never',
    'selector-class-pattern': null,
    'selector-pseudo-element-no-unknown': [
      true,
      { ignorePseudoElements: ['v-deep'] },
    ],
    'selector-type-no-unknown': null,
    'unit-no-unknown': null,
    'no-empty-source': null,
  },
};
