/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About/About.vue')['default']
    BackToTop: typeof import('./components/BackToTop/BackToTop.vue')['default']
    EvrstLogo: typeof import('./components/EvrstLogo/EvrstLogo.vue')['default']
    Footer: typeof import('./components/Footer/Footer.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    Hero: typeof import('./components/Hero/Hero.vue')['default']
    HtmlTitle: typeof import('./components/HtmlTitle/HtmlTitle.vue')['default']
    Meta: typeof import('./components/Meta/Meta.vue')['default']
    Outro: typeof import('./components/Outro/Outro.vue')['default']
    ResponsiveImage: typeof import('./components/ResponsiveImg/ResponsiveImage.vue')['default']
    RocketScene: typeof import('./components/RocketScene/RocketScene.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./components/Section/Section.vue')['default']
    SectionButton: typeof import('./components/SectionButton/SectionButton.vue')['default']
    Team: typeof import('./components/Team/Team.vue')['default']
  }
}
