/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./components/Chrome/BackToTop.vue')['default']
    Countdown: typeof import('./components/Hero/Countdown.vue')['default']
    EmptyNote: typeof import('./components/States/EmptyNote.vue')['default']
    Events: typeof import('./components/Home/Events.vue')['default']
    EvrstLogo: typeof import('./components/Brand/EvrstLogo.vue')['default']
    EvrstMarquee: typeof import('./components/Brand/EvrstMarquee.vue')['default']
    FetchError: typeof import('./components/States/FetchError.vue')['default']
    FormField: typeof import('./components/Form/FormField.vue')['default']
    FormProgress: typeof import('./components/Form/FormProgress.vue')['default']
    Hero: typeof import('./components/Hero/Hero.vue')['default']
    HeroParallax: typeof import('./components/Hero/HeroParallax.vue')['default']
    HeroSays: typeof import('./components/Hero/HeroSays.vue')['default']
    HtmlTitle: typeof import('./components/HtmlTitle/HtmlTitle.vue')['default']
    JoinCta: typeof import('./components/Home/JoinCta.vue')['default']
    LocaleToggle: typeof import('./components/Chrome/LocaleToggle.vue')['default']
    Manifesto: typeof import('./components/Home/Manifesto.vue')['default']
    Mentors: typeof import('./components/Home/Mentors.vue')['default']
    Meta: typeof import('./components/Meta/Meta.vue')['default']
    ObudaLogo: typeof import('./components/Brand/ObudaLogo.vue')['default']
    OptionPills: typeof import('./components/Form/OptionPills.vue')['default']
    Programme: typeof import('./components/Home/Programme.vue')['default']
    ResponsiveImage: typeof import('./components/ResponsiveImg/ResponsiveImage.vue')['default']
    Reveal: typeof import('./components/Motion/Reveal.vue')['default']
    Rocket: typeof import('./components/Home/Rocket.vue')['default']
    RocketBlueprint: typeof import('./components/Home/RocketBlueprint.vue')['default']
    RocketGlyph: typeof import('./components/Brand/RocketGlyph.vue')['default']
    RocketSvg: typeof import('./components/Hero/RocketSvg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rule: typeof import('./components/Sections/Rule.vue')['default']
    SectionShell: typeof import('./components/Sections/SectionShell.vue')['default']
    SelectInput: typeof import('./components/Form/SelectInput.vue')['default']
    SiteFooter: typeof import('./components/Chrome/SiteFooter.vue')['default']
    SiteHeader: typeof import('./components/Chrome/SiteHeader.vue')['default']
    SiteNav: typeof import('./components/Chrome/SiteNav.vue')['default']
    Skeleton: typeof import('./components/States/Skeleton.vue')['default']
    Sponsors: typeof import('./components/Home/Sponsors.vue')['default']
    Starfield: typeof import('./components/Hero/Starfield.vue')['default']
    Team: typeof import('./components/Home/Team.vue')['default']
    TextArea: typeof import('./components/Form/TextArea.vue')['default']
    TextInput: typeof import('./components/Form/TextInput.vue')['default']
    ToastHost: typeof import('./components/Form/ToastHost.vue')['default']
  }
}
